# Generated by Django 3.2.9 on 2021-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.IntegerField()),
                ('Positive_count', models.IntegerField()),
                ('Negative_count', models.IntegerField()),
                ('Neutral_count', models.IntegerField()),
                ('Pos_Neg_words', models.IntegerField()),
                ('Total_words', models.IntegerField()),
                ('Positive_percent', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('Negative_percent', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('Neutral_percent', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('Pos_percent', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('Neg_percent', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAggregateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.IntegerField()),
                ('number_of_positive_sentence', models.IntegerField()),
                ('number_of_negative_sentence', models.IntegerField()),
                ('number_of_neutral_sentence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VID_ID', models.CharField(max_length=100)),
                ('Company_ID', models.CharField(max_length=100)),
                ('Survey_ID', models.IntegerField()),
                ('Cust_ID', models.IntegerField()),
                ('question', models.IntegerField()),
                ('transcript', models.CharField(max_length=100)),
                ('SpeakTime', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('num_words', models.IntegerField()),
                ('Hurriness', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('Score', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('AverageConfidence', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='WordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VID', models.CharField(max_length=100)),
                ('Company_ID', models.CharField(max_length=100)),
                ('Survey_ID', models.IntegerField()),
                ('Cust_ID', models.IntegerField()),
                ('question', models.IntegerField()),
                ('start', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('end', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('conf', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('content', models.CharField(max_length=100)),
                ('pron', models.CharField(max_length=100)),
                ('mean_time', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('der_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('MF', models.IntegerField()),
                ('net_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('sec', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('Sentiment', models.CharField(max_length=100)),
                ('SCORE', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
            ],
        ),
    ]
