# Generated by Django 3.2.9 on 2022-01-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LexiconData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30, null=True)),
                ('sentiment', models.CharField(max_length=30, null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(max_length=50)),
                ('transcript', models.TextField()),
                ('video_name', models.URLField()),
                ('question', models.IntegerField(default=0)),
                ('average_confidence', models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True)),
                ('total_words', models.IntegerField(default=0)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True)),
                ('average_score', models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True)),
                ('score_sd', models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True)),
                ('score_per_statement', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('end_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('content', models.CharField(blank=True, max_length=30, null=True)),
                ('pron', models.CharField(blank=True, max_length=30, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('mean_time', models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True)),
                ('der_score', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('mf', models.IntegerField(default=0)),
                ('net_score', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True)),
                ('second', models.IntegerField(default=0)),
                ('sentiment', models.CharField(default='NEU', max_length=30, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('question', models.IntegerField(default=0)),
                ('transcript_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_details', to='aws_transcript.transcript')),
            ],
        ),
    ]
